---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-controller-manager
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: bizfly-cloud-controller-manager
  namespace: kube-system
  labels:
    k8s-app: bizfly-cloud-controller-manager
spec:
  selector:
    matchLabels:
      k8s-app: bizfly-cloud-controller-manager
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: bizfly-cloud-controller-manager
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      securityContext:
        runAsUser: 1001
      tolerations:
      - key: node.cloudprovider.kubernetes.io/uninitialized
        value: "true"
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      serviceAccountName: cloud-controller-manager
      containers:
        - name: bizfly-cloud-controller-manager
          image: cr-hn-1.vccloud.vn/17a1c3c952c84b3e84a82ddd48364938/bizfly-cloud-controller-manager:latest
          args:
            - /bin/bizfly-cloud-controller-manager
            - --v=1
            - --cloud-provider=bizflycloud
            - --use-service-account-credentials=true
            - --address=127.0.0.1
          volumeMounts:
            - mountPath: /etc/kubernetes/pki
              name: k8s-certs
              readOnly: true
            - mountPath: /etc/ssl/certs
              name: ca-certs
              readOnly: true
          resources:
            requests:
              cpu: 200m
          env:
            - name: BIZFLYCLOUD_EMAIL
              valueFrom:
                secretKeyRef:
                  name: bizflycloud
                  key: email
            - name: BIZFLYCLOUD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bizflycloud
                  key: password
      hostNetwork: true
      volumes:
      - hostPath:
          path: /etc/kubernetes/pki
          type: DirectoryOrCreate
        name: k8s-certs
      - hostPath:
          path: /etc/ssl/certs
          type: DirectoryOrCreate
        name: ca-certs