name: Run E2E Test
on:
  pull_request:
    types:
      - closed
    branches:
      - master
jobs:
  build_and_push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set output
        id: vars
        run: |
          TAG=$(echo $GITHUB_SHA | cut -c1-5)
          IMAGE="${{ vars.IMAGE_PREFIX }}:$TAG"
          echo $IMAGE
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Check output
        run: |
          echo $IMAGE

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          registry: cr-hn-1.bizflycloud.vn
          name: ${{ env.IMAGE }}
          username: ${{ secrets.ACCOUNT_EMAIL }}
          password: ${{ secrets.ACCOUNT_PASSWORD }}

  Run-e2e-test:
    if: github.event.pull_request.merged == true
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - uses: actions/checkout@master

      - name: Set output
        id: vars
        run: |
          TAG=$(echo $GITHUB_SHA | cut -c1-5)
          IMAGE="${{ vars.IMAGE_PREFIX }}:$TAG"
          echo $IMAGE
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Check output
        run: |
          echo $IMAGE

      - name: Run tests
        run: |
          cd e2e
          go install github.com/onsi/ginkgo/v2/ginkgo
          export PATH=$PATH:$(go env GOPATH)/bin
          ./run.sh \
            -v '${{ vars.VERSION_UID }}' \
            -P '${{ vars.VPC_ID }}' \
            -u '${{ secrets.APP_CRED_ID }}' \
            -p '${{ secrets.APP_CRED_SECRET }}' \
            --email '${{ secrets.ACCOUNT_EMAIL }}' \
            --password '${{ secrets.ACCOUNT_PASSWORD }}' \
            --token '${{ secrets.SECRET_TOKEN }}' \
            --image ${{ env.IMAGE }}
