name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    #container: docker:dind
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
    - run: |
          docker --version
          go version
          ls
    - name: Build images
      run: | 
        echo ${{ secrets.USER_CLOUD }} 
        VERSION=v0.1
        docker login -u ${{ secrets.USER_CLOUD }} -p ${{ secrets.PASS }}  cr-hn-1.vccloud.vn/e221625fe113449d8360f6ead78fb884/test
        docker build -t cr-hn-1.vccloud.vn/e221625fe113449d8360f6ead78fb884/test:${VERSION} -f Dockerfile .
        docker push cr-hn-1.vccloud.vn/e221625fe113449d8360f6ead78fb884/test:${VERSION}
        
    #- name: Build
    #  run: docker build -t bizfly-cloud-controller-manager:v0.1 -f Dockerfile .

    #- name: Test
    #  run: go test
